services:
  frontend:
    build:
      context: ./frontend
    environment:
      VITE_BACKEND_URL: http://server:3001
    container_name: bloglist-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend_dist:/usr/src/app/dist

  backend:
    build:
      context: ./backend
    container_name: bloglist-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - backend
      - frontend

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo_data:/data/db
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
